---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure keepalived is installed
      ansible.builtin.stat:
        path: /usr/sbin/keepalived
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg

    - name: Ensure keepalived is running
      ansible.builtin.service:
        name: keepalived
        state: started
      check_mode: true
      register: _keepalived_service
      failed_when: _keepalived_service.changed
